# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - '6380:6380'
      - '16380:16380'
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=6380'
      - 'REDIS_PORT_NUMBER=6380'
      - 'REDIS_PASSWORD=123456'
      - 'REDIS_NODES=redis-node-0:6380 redis-node-1:6381 redis-node-2:6382'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6380'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16380'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-1
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - '6381:6381'
      - '16381:16381'
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=6381'
      - 'REDIS_PORT_NUMBER=6381'
      - 'REDIS_PASSWORD=123456'
      - 'REDIS_NODES=redis-node-0:6380 redis-node-1:6381 redis-node-2:6382'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6381'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16381'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    ports:
      - '6382:6382'
      - '16382:16382'
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=6382'
      - 'REDIS_PORT_NUMBER=6382'
      - 'REDIS_PASSWORD=123456'
      - 'REDISCLI_AUTH=123456'
      - 'REDIS_NODES=redis-node-0:6380 redis-node-1:6381 redis-node-2:6382'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6382'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16382'
      - 'REDIS_CLUSTER_REPLICAS=0'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
