# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - '7000:7000'
      - '17000:17000'
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=7000'
      - 'REDIS_PORT_NUMBER=7000'
      - 'REDIS_PASSWORD=123456'
      - 'REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=7000'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17000'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-1
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - '7001:7001'
      - '17001:17001'
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=7001'
      - 'REDIS_PORT_NUMBER=7001'
      - 'REDIS_PASSWORD=123456'
      - 'REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=7001'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17001'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-node-2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    ports:
      - '7002:7002'
      - '17002:17002'
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_MASTER_PORT_NUMBER=7002'
      - 'REDIS_PORT_NUMBER=7002'
      - 'REDIS_PASSWORD=123456'
      - 'REDISCLI_AUTH=123456'
      - 'REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=172.17.1.8'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=7002'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17002'
      - 'REDIS_CLUSTER_REPLICAS=0'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
